### ISSUE TITLE
Building a native library

### ISSUE THREAD

**Issue by torkleyy** [tomaka/android-rs-glue#135]
How can I use a native library I've built for Android? More specifically, I'd like to build `rust-sdl2`, however it seems `cargo-apk` cannot find the built SDL2 libraries.

**Comment by tomaka** [comment]
In theory this should work as in any non-Android platform: http://doc.crates.io/build-script.html#overriding-build-scripts

**Comment by TatriX** [comment]
I'm trying to build a [ggez](https://github.com/ggez/ggez) based app, which uses `SDL2`.
```
 = note: /usr/local/android-ndk-r15b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lSDL2
          collect2: error: ld returned 1 exit status
          Error while executing gcc
```
What steps should I do to fix that problem? Should I create an updated docker image, which will install `SDL2` before running `cargo apk build`?

**Comment by tomaka** [comment]
> I installed into docker image libsdl2-dev libsdl2-2.0 and it didn't help

That's because these packages contain a libsdl2 that targets your current platform, while you need a libsdl2 that targets Android.

**Comment by TatriX** [comment]
Could you please point me to the docs on how I can do it?

**Comment by TatriX** [comment]
If I have `libSDL2.so` built for android, where should I place it so `ld` could find it?

**Comment by tomaka** [comment]
See the docs here: http://doc.crates.io/build-script.html#overriding-build-scripts

Put a `.cargo/config` file somewhere (or in your HOME), and put something like this inside:

```toml
[target.arm-linux-androideabi.SDL2]   # refers to this line: https://github.com/Rust-SDL2/rust-sdl2/blob/master/sdl2-sys/Cargo.toml#L11
rustc-link-search = ["/some/path"]
rustc-link-lib = ["SDL2"]   # name of the file, with `lib` and `.so` removed
```
