### ISSUE TITLE
Simple app panics on glutin initialization

### ISSUE THREAD

**Issue by ozkriff** [tomaka/android-rs-glue#93]
adb logcat:

```
...
D/RustAndroidGlueStdouterr(27747): Entering android_main
D/RustAndroidGlueStdouterr(27747): Creating application thread
...
D/RustAndroidGlueStdouterr(27747): thread '<main>' panicked at 'The application was not initialized from android_main', /home/ozkriff/.cargo/registry/src/github.com-88ac128001ac3a9a/android_glue-0.1.3/src/lib.rs:490
...
```

src/main.rs:

```rust
#[macro_use]
extern crate glium;

use glium::{DisplayBuild, Surface};

fn main() {
    std::env::set_var("RUST_BACKTRACE", "1");
    let window_builder = glium::glutin::WindowBuilder::new();
    let display = window_builder.build_glium().unwrap();
    loop {
        let mut target = display.draw();
        target.clear_color(0.0, 0.0, 1.0, 1.0);
        target.finish().unwrap();
        for e in display.poll_events() {
            if let glium::glutin::Event::Closed = e {
                return;
            }
        }
    }
}
```

Cargo.toml:

```toml
[package]
name = "nirgal"
version = "0.1.0"
authors = ["Andrey Lesnikov <ozkriff@gmail.com>"]

[dependencies]
glium = "*"
```
